# Generated by Django 4.0.6 on 2022-07-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='event_id',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='event_id',
            field=models.ManyToManyField(to='services.evantmodel'),
        ),
    ]
