# Generated by Django 4.0.6 on 2022-07-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_menumodel_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='event_id',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='event_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.evantmodel'),
            preserve_default=False,
        ),
    ]
