# Generated by Django 4.0.6 on 2022-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_servicemodel_file_tablemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systeminfofilemodel',
            name='systeminfo_id',
        ),
        migrations.AddField(
            model_name='systeminfomodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='info/'),
        ),
        migrations.AlterField(
            model_name='systeminfofilemodel',
            name='file',
            field=models.FileField(blank=True, upload_to='gallery/'),
        ),
    ]
