# Generated by Django 4.0.6 on 2022-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_systeminfofilemodel_systeminfo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systeminfofilemodel',
            options={'verbose_name_plural': 'Галерея'},
        ),
        migrations.AddField(
            model_name='evantmodel',
            name='definition',
            field=models.CharField(default='wedding', max_length=50),
            preserve_default=False,
        ),
    ]
